forexAI::AudioFX
static void forexAI.AudioFX.Play(string audioFileName)
References forexAI.Configuration.audioEnabled.
Referenced by forexAI.AudioFX.Fail, forexAI.AudioFX.GoodWork, forexAI.AudioFX.LowBalance, forexAI.AudioFX.NewDay, forexAI.AudioFX.Profit, forexAI.AudioFX.TheBroken, forexAI.AudioFX.Wipe.
static void forexAI.AudioFX.Wipe()
References forexAI.AudioFX.Play, forexAI.Configuration.wipeWav.
static void forexAI.AudioFX.NewDay()
References forexAI.Configuration.newDayWAV, forexAI.AudioFX.Play.
static void forexAI.AudioFX.Fail()
References forexAI.Configuration.failWav, forexAI.AudioFX.Play.
static void forexAI.AudioFX.Profit()
References forexAI.AudioFX.Play, forexAI.Configuration.profitWAV.
static void forexAI.AudioFX.TheBroken()
References forexAI.Configuration.brokenWAV, forexAI.AudioFX.Play.
static void forexAI.AudioFX.GoodWork()
References forexAI.Configuration.goodWorkWAV, forexAI.AudioFX.Play.
Referenced by forexAI.ForexAI.start.
static void forexAI.AudioFX.LowBalance()
References forexAI.Configuration.lowBalanceWAV, forexAI.AudioFX.Play.