forexAI::ForexAI
double forexAI.ForexAI.orderLots
double forexAI.ForexAI.maxNegativeSpend
Referenced by forexAI.ForexAI.CloseNegativeOrders.
double forexAI.ForexAI.trailingBorder
Referenced by forexAI.ForexAI.TrailPositions.
double forexAI.ForexAI.trailingStop
Referenced by forexAI.ForexAI.InitVariables, forexAI.ForexAI.TrailPositions.
double forexAI.ForexAI.stableBigChangeFactor
double forexAI.ForexAI.tradeEnterProbabilityMin
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.rejectTradeProbability
Referenced by forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.minLossForCounterTrade
Referenced by forexAI.ForexAI.TryEnterCounterTrade.
bool forexAI.ForexAI.useOptimizedLots
int forexAI.ForexAI.maxOrdersParallel
Referenced by forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
int forexAI.ForexAI.minStableTrendBarForEnter
Referenced by forexAI.ForexAI.TryEnterTrade.
int forexAI.ForexAI.maxStableTrendBarForEnter
int forexAI.ForexAI.minTradePeriodBars
Referenced by forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
bool forexAI.ForexAI.counterTrading
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.countedMeasuredProbabilityBars
Referenced by forexAI.ForexAI.init.
double forexAI.ForexAI.maxOrderOpenHours
double forexAI.ForexAI.minOrderDistance
Referenced by forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.orderAliveHours
Referenced by forexAI.ForexAI.CloseNegativeOrders.
double forexAI.ForexAI.collapseEnterLots
double forexAI.ForexAI.counterTradeLots
double forexAI.ForexAI.collapseChangePoints
Referenced by forexAI.ForexAI.CheckForMarketCollapse.
Random forexAI.ForexAI.random
Referenced by forexAI.ForexAI.InitVariables.
List<Order> forexAI.ForexAI.historyOrders
Referenced by forexAI.ForexAI.FillHistoryOrdersStatistics.
List<Order> forexAI.ForexAI.activeOrders
Referenced by forexAI.ForexAI.CloseNegativeOrders, forexAI.ForexAI.DrawStats, forexAI.ForexAI.SyncOrders, forexAI.ForexAI.TrailPositions.
Storage forexAI.ForexAI.storage
Config forexAI.ForexAI.config
Referenced by forexAI.ForexAI.InitVariables, forexAI.ForexAI.ScanNetworks.
PerformanceCounter forexAI.ForexAI.cpuCounter
Referenced by forexAI.ForexAI.init.
DirectoryInfo [] forexAI.ForexAI.networkDirs
Referenced by forexAI.ForexAI.InitNetworks, forexAI.ForexAI.ScanNetworks.
NeuralNet forexAI.ForexAI.forexFannNetwork
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.InitNetworks, forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
TrainingData forexAI.ForexAI.trainingData
Referenced by forexAI.ForexAI.TestNetworkHitRatio, forexAI.ForexAI.TestNetworkMSE.
Process forexAI.ForexAI.currentProcess
Referenced by forexAI.ForexAI.InitVariables.
TrainingData forexAI.ForexAI.testData
Referenced by forexAI.ForexAI.TestNetworkHitRatio, forexAI.ForexAI.TestNetworkMSE.
Stopwatch forexAI.ForexAI.runWatch
Referenced by forexAI.ForexAI.init, forexAI.ForexAI.start.
Version forexAI.ForexAI.version
Referenced by forexAI.ForexAI.ShowBanner.
MqlApi forexAI.ForexAI.mqlApi
Referenced by forexAI.ForexAI.init, forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
string forexAI.ForexAI.networkId
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.LoadNetwork.
string forexAI.ForexAI.fannNetworkDirName
Referenced by forexAI.ForexAI.LoadNetwork.
string forexAI.ForexAI.inputLayerActivationFunction
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.LoadNetwork.
string forexAI.ForexAI.middleLayerActivationFunction
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.LoadNetwork.
string forexAI.ForexAI.labelID
Referenced by forexAI.ForexAI.DrawStats.
string forexAI.ForexAI.type
string forexAI.ForexAI.symbol
Referenced by forexAI.ForexAI.AddLabel, forexAI.ForexAI.AddVerticalLabel, forexAI.ForexAI.CloseBuys, forexAI.ForexAI.CloseNegativeOrders, forexAI.ForexAI.CloseSells, forexAI.ForexAI.InitVariables, forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell, forexAI.ForexAI.SyncOrders.
string forexAI.ForexAI.charizedOrdersHistory
Referenced by forexAI.ForexAI.CloseBuys, forexAI.ForexAI.CloseSells, forexAI.ForexAI.RenderVisualizedzedHistory.
string forexAI.ForexAI.functionsTextContent
Referenced by forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
double forexAI.ForexAI.trainHitRatio
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.TestNetworkHitRatio.
double forexAI.ForexAI.testHitRatio
Referenced by forexAI.ForexAI.TestNetworkHitRatio.
double forexAI.ForexAI.total
Referenced by forexAI.ForexAI.DrawStats.
double forexAI.ForexAI.spends
Referenced by forexAI.ForexAI.DrawStats.
double forexAI.ForexAI.profit
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.SyncOrders.
double forexAI.ForexAI.minStopLevel
Referenced by forexAI.ForexAI.TrailPositions.
double forexAI.ForexAI.ordersStopPoints
Referenced by forexAI.ForexAI.InitVariables.
double forexAI.ForexAI.risky2_Risk
double forexAI.ForexAI.risky2_Lots
double forexAI.ForexAI.risky2_LotDigits
double forexAI.ForexAI.minlot
Referenced by forexAI.ForexAI.InitVariables.
double forexAI.ForexAI.maxlot
Referenced by forexAI.ForexAI.InitVariables.
double forexAI.ForexAI.leverage
double forexAI.ForexAI.lotsize
Referenced by forexAI.ForexAI.InitVariables.
double forexAI.ForexAI.stoplevel
Referenced by forexAI.ForexAI.InitVariables.
double [] forexAI.ForexAI.prevNetworkOutputBuy
Referenced by forexAI.ForexAI.IsBadNetwork, forexAI.ForexAI.LoadNetwork.
double [] forexAI.ForexAI.prevNetworkOutputSell
Referenced by forexAI.ForexAI.IsBadNetwork, forexAI.ForexAI.LoadNetwork.
double [] forexAI.ForexAI.fannNetworkOutput
Referenced by forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
double [] forexAI.ForexAI.prevBuyProbability
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.init.
double [] forexAI.ForexAI.prevSellProbability
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.init.
float forexAI.ForexAI.testMse
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.TestNetworkMSE.
float forexAI.ForexAI.trainMse
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.TestNetworkMSE.
long forexAI.ForexAI.lastDrawStatsTimestamp
Referenced by forexAI.ForexAI.start.
long forexAI.ForexAI.lastMemoryStatsDumpTimesamp
Referenced by forexAI.ForexAI.start.
bool forexAI.ForexAI.reassembleStageOverride
Referenced by forexAI.ForexAI.init, forexAI.ForexAI.InitNetworks, forexAI.ForexAI.start.
bool forexAI.ForexAI.hasNoticedLowBalance
Referenced by forexAI.ForexAI.start.
bool forexAI.ForexAI.profitTrailing
bool forexAI.ForexAI.hasNightReported
Referenced by forexAI.ForexAI.start.
bool forexAI.ForexAI.hasMorningReported
Referenced by forexAI.ForexAI.start.
bool forexAI.ForexAI.neuralNetworkBootstrapped
Referenced by forexAI.ForexAI.init, forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
bool forexAI.ForexAI.hasIncreasedUnstableTrendBar
bool forexAI.ForexAI.networkIsGood
Referenced by forexAI.ForexAI.init.
int forexAI.ForexAI.stableTrendCurrentBar
int forexAI.ForexAI.spendSells
Referenced by forexAI.ForexAI.CloseNegativeOrders, forexAI.ForexAI.DrawStats, forexAI.ForexAI.FillHistoryOrdersStatistics, forexAI.ForexAI.RenderVisualizedzedHistory.
int forexAI.ForexAI.spendBuys
Referenced by forexAI.ForexAI.CloseNegativeOrders, forexAI.ForexAI.DrawStats, forexAI.ForexAI.FillHistoryOrdersStatistics, forexAI.ForexAI.RenderVisualizedzedHistory.
int forexAI.ForexAI.profitSells
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.FillHistoryOrdersStatistics, forexAI.ForexAI.RenderVisualizedzedHistory.
int forexAI.ForexAI.profitBuys
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.FillHistoryOrdersStatistics, forexAI.ForexAI.RenderVisualizedzedHistory.
int forexAI.ForexAI.totalSpends
Referenced by forexAI.ForexAI.DrawStats.
int forexAI.ForexAI.totalProfits
Referenced by forexAI.ForexAI.DrawStats.
int forexAI.ForexAI.openedBuys
int forexAI.ForexAI.openedSells
int forexAI.ForexAI.inputDimension
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
int forexAI.ForexAI.currentTicket
int forexAI.ForexAI.dayOperationsCount
Referenced by forexAI.ForexAI.CloseBuys, forexAI.ForexAI.CloseNegativeOrders, forexAI.ForexAI.CloseSells, forexAI.ForexAI.DrawStats, forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell, forexAI.ForexAI.start, forexAI.ForexAI.TrailPositions.
int forexAI.ForexAI.ordersTotal
int forexAI.ForexAI.previousBars
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.barsPerDay
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.startTime
Referenced by forexAI.ForexAI.deinit, forexAI.ForexAI.init.
int forexAI.ForexAI.previousBankDay
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.totalOperationsCount
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.start.
int forexAI.ForexAI.buysPermitted
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.sellsPermitted
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.currentDay
Referenced by forexAI.ForexAI.init.
int forexAI.ForexAI.stableTrendBar
Referenced by forexAI.ForexAI.start, forexAI.ForexAI.TryEnterTrade.
int forexAI.ForexAI.networkFunctionsCount
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.start.
int forexAI.ForexAI.unstableTrendBar
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.lastTradeBar
Referenced by forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell.
int forexAI.ForexAI.marketCollapsedBar
Referenced by forexAI.ForexAI.CheckForMarketCollapse.
int forexAI.ForexAI.ordersCount
Referenced by forexAI.ForexAI.CheckForAutoClose, forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
int forexAI.ForexAI.tradeBarPeriodPass
Referenced by forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
int forexAI.ForexAI.buysCount
Referenced by forexAI.ForexAI.CloseBuys.
int forexAI.ForexAI.sellsCount
Referenced by forexAI.ForexAI.CloseSells.
double forexAI.ForexAI.buyProbability
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.IsBadNetwork, forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.sellProbability
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.IsBadNetwork, forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.ordersProfit
double forexAI.ForexAI.diffProbability
TrendDirection forexAI.ForexAI.collapseDirection
Referenced by forexAI.ForexAI.CheckForMarketCollapse, forexAI.ForexAI.TryEnterCounterTrade.
double forexAI.ForexAI.activeIncome
Referenced by forexAI.ForexAI.DrawStats.
double forexAI.ForexAI.activeProfit
Referenced by forexAI.ForexAI.CheckForAutoClose, forexAI.ForexAI.DrawStats.
double forexAI.ForexAI.buysProfit
Referenced by forexAI.ForexAI.CheckForAutoClose, forexAI.ForexAI.TryEnterCounterTrade.
double forexAI.ForexAI.sellsProfit
Referenced by forexAI.ForexAI.CheckForAutoClose, forexAI.ForexAI.TryEnterCounterTrade.
double forexAI.ForexAI.activeLoss
Referenced by forexAI.ForexAI.CheckForAutoClose, forexAI.ForexAI.DrawStats.
double forexAI.ForexAI.lotsOptimizedV3
double forexAI.ForexAI.lotsOptimizedV2
Referenced by forexAI.ForexAI.CheckForMarketCollapse, forexAI.ForexAI.TryEnterCounterTrade.
double forexAI.ForexAI.lotsOptimizedV1
Referenced by forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell.
bool forexAI.ForexAI.isTrendStable
Referenced by forexAI.ForexAI.DrawStats, forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.closestBuyDistance
Referenced by forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
double forexAI.ForexAI.closestSellDistance
Referenced by forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
override int forexAI.ForexAI.start()
References forexAI.ForexAI.AddLabel, forexAI.ForexAI.barsPerDay, forexAI.ForexAI.buysPermitted, forexAI.ForexAI.CheckForAutoClose, forexAI.ForexAI.CheckForMarketCollapse, forexAI.ForexAI.CloseNegativeOrders, forexAI.ForexAI.counterTrading, forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.DrawStats, forexAI.Reassembler.Execute, forexAI.ForexAI.fannNetworkOutput, forexAI.ForexAI.FillHistoryOrdersStatistics, forexAI.ForexAI.forexFannNetwork, forexAI.ForexAI.functionsTextContent, forexAI.AudioFX.GoodWork, forexAI.ForexAI.hasMorningReported, forexAI.ForexAI.hasNightReported, forexAI.ForexAI.hasNoticedLowBalance, forexAI.ForexAI.InitNetworks, forexAI.ForexAI.inputDimension, forexAI.ForexAI.IsBadNetwork, forexAI.ForexAI.lastDrawStatsTimestamp, forexAI.ForexAI.lastMemoryStatsDumpTimesamp, forexAI.ForexAI.mqlApi, forexAI.ForexAI.networkFunctionsCount, forexAI.ForexAI.neuralNetworkBootstrapped, forexAI.YRandom.Next, forexAI.ForexAI.previousBankDay, forexAI.ForexAI.previousBars, forexAI.ForexAI.reassembleStageOverride, forexAI.ForexAI.RenderVisualizedzedHistory, forexAI.ForexAI.runWatch, forexAI.ForexAI.sellsPermitted, forexAI.ForexAI.stableTrendBar, forexAI.ForexAI.SyncOrders, forexAI.ForexAI.totalOperationsCount, forexAI.ForexAI.TrailPositions, forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade, forexAI.Configuration.tryExperimentalFeatures, forexAI.ForexAI.unstableTrendBar.
override int forexAI.ForexAI.init()
References forexAI.Configuration.audioEnabled, forexAI.ForexAI.countedMeasuredProbabilityBars, forexAI.ForexAI.cpuCounter, forexAI.ForexAI.currentDay, forexAI.ForexAI.DumpInfo, forexAI.ForexAI.InitNetworks, forexAI.ForexAI.InitVariables, forexAI.Experimental.IsHardwareForcesConnected, forexAI.ForexAI.ListGlobalVariables, forexAI.ForexAI.mqlApi, forexAI.ForexAI.networkIsGood, forexAI.ForexAI.neuralNetworkBootstrapped, forexAI.ForexAI.prevBuyProbability, forexAI.ForexAI.prevSellProbability, forexAI.ForexAI.reassembleStageOverride, forexAI.ForexAI.runWatch, forexAI.ForexAI.ShowBanner, forexAI.ForexAI.startTime, forexAI.Configuration.tryExperimentalFeatures, forexAI.Configuration.XRandomLogFileName, forexAI.Configuration.YRandomLogFileName.
override int forexAI.ForexAI.deinit()
References forexAI.ForexAI.startTime.
void forexAI.ForexAI.InitNetworks()
References forexAI.ForexAI.forexFannNetwork, forexAI.ForexAI.LoadNetwork, forexAI.ForexAI.networkDirs, forexAI.ForexAI.reassembleStageOverride, forexAI.ForexAI.ScanNetworks, forexAI.ForexAI.TestNetworkHitRatio, forexAI.ForexAI.TestNetworkMSE.
Referenced by forexAI.ForexAI.init, forexAI.ForexAI.start.
bool forexAI.ForexAI.IsBadNetwork()
References forexAI.ForexAI.buyProbability, forexAI.ForexAI.prevNetworkOutputBuy, forexAI.ForexAI.prevNetworkOutputSell, forexAI.ForexAI.sellProbability.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.SyncOrders()
References forexAI.ForexAI.activeOrders, forexAI.ForexAI.profit, forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.InitVariables()
References forexAI.ForexAI.config, forexAI.ForexAI.currentProcess, forexAI.ForexAI.lotsize, forexAI.ForexAI.maxlot, forexAI.ForexAI.minlot, forexAI.Configuration.mysqlEnabled, forexAI.YRandom.Next, forexAI.ForexAI.ordersStopPoints, forexAI.ForexAI.random, forexAI.ForexAI.stoplevel, forexAI.ForexAI.symbol, forexAI.ForexAI.trailingStop.
Referenced by forexAI.ForexAI.init.
void forexAI.ForexAI.TryEnterTrade()
References forexAI.ForexAI.buyProbability, forexAI.ForexAI.closestBuyDistance, forexAI.ForexAI.closestSellDistance, forexAI.ForexAI.isTrendStable, forexAI.ForexAI.maxOrdersParallel, forexAI.ForexAI.minOrderDistance, forexAI.ForexAI.minStableTrendBarForEnter, forexAI.ForexAI.minTradePeriodBars, forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell, forexAI.ForexAI.ordersCount, forexAI.ForexAI.rejectTradeProbability, forexAI.ForexAI.sellProbability, forexAI.ForexAI.stableTrendBar, forexAI.ForexAI.tradeBarPeriodPass, forexAI.ForexAI.tradeEnterProbabilityMin.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.TryEnterCounterTrade()
References forexAI.ForexAI.buyProbability, forexAI.ForexAI.buysProfit, forexAI.ForexAI.closestBuyDistance, forexAI.ForexAI.closestSellDistance, forexAI.ForexAI.collapseDirection, forexAI.ForexAI.lotsOptimizedV2, forexAI.ForexAI.maxOrdersParallel, forexAI.ForexAI.minLossForCounterTrade, forexAI.ForexAI.minOrderDistance, forexAI.ForexAI.minTradePeriodBars, forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell, forexAI.ForexAI.ordersCount, forexAI.ForexAI.sellProbability, forexAI.ForexAI.sellsProfit, forexAI.ForexAI.tradeBarPeriodPass.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.ListGlobalVariables()
Referenced by forexAI.ForexAI.init.
void forexAI.ForexAI.CheckForAutoClose()
References forexAI.ForexAI.activeLoss, forexAI.ForexAI.activeProfit, forexAI.ForexAI.buysProfit, forexAI.ForexAI.CloseAllOrders, forexAI.ForexAI.ordersCount, forexAI.ForexAI.sellsProfit.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.CloseAllOrders()
References forexAI.ForexAI.CloseBuys, forexAI.ForexAI.CloseSells.
Referenced by forexAI.ForexAI.CheckForAutoClose.
void forexAI.ForexAI.CheckForMarketCollapse()
References forexAI.ForexAI.AddVerticalLabel, forexAI.ForexAI.collapseChangePoints, forexAI.ForexAI.collapseDirection, forexAI.ForexAI.lotsOptimizedV2, forexAI.ForexAI.marketCollapsedBar, forexAI.ForexAI.OpenBuy, forexAI.ForexAI.OpenSell.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.FillHistoryOrdersStatistics()
References forexAI.ForexAI.historyOrders, forexAI.ForexAI.profitBuys, forexAI.ForexAI.profitSells, forexAI.ForexAI.spendBuys, forexAI.ForexAI.spendSells.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.LoadNetwork(string dirName)
References forexAI.Reassembler.Execute, forexAI.ForexAI.fannNetworkDirName, forexAI.ForexAI.fannNetworkOutput, forexAI.ForexAI.forexFannNetwork, forexAI.ForexAI.functionsTextContent, forexAI.ForexAI.inputDimension, forexAI.ForexAI.inputLayerActivationFunction, forexAI.ForexAI.middleLayerActivationFunction, forexAI.ForexAI.mqlApi, forexAI.ForexAI.networkFunctionsCount, forexAI.ForexAI.networkId, forexAI.ForexAI.neuralNetworkBootstrapped, forexAI.ForexAI.prevNetworkOutputBuy, forexAI.ForexAI.prevNetworkOutputSell.
Referenced by forexAI.ForexAI.InitNetworks.
void forexAI.ForexAI.ScanNetworks()
References forexAI.ForexAI.config, forexAI.ForexAI.networkDirs, forexAI.Configuration.rootDirectory.
Referenced by forexAI.ForexAI.InitNetworks.
void forexAI.ForexAI.TestNetworkMSE()
References forexAI.Configuration.rootDirectory, forexAI.ForexAI.testData, forexAI.ForexAI.testMse, forexAI.ForexAI.trainingData, forexAI.ForexAI.trainMse.
Referenced by forexAI.ForexAI.InitNetworks.
void forexAI.ForexAI.TestNetworkHitRatio()
References forexAI.ForexAI.CalculateHitRatio, forexAI.ForexAI.testData, forexAI.ForexAI.testHitRatio, forexAI.ForexAI.trainHitRatio, forexAI.ForexAI.trainingData.
Referenced by forexAI.ForexAI.InitNetworks.
double forexAI.ForexAI.CalculateHitRatio(double[][] inputs, double[][] desiredOutputs)
Referenced by forexAI.ForexAI.TestNetworkHitRatio.
void forexAI.ForexAI.CloseNegativeOrders()
References forexAI.ForexAI.activeOrders, forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.maxNegativeSpend, forexAI.ForexAI.orderAliveHours, forexAI.ForexAI.spendBuys, forexAI.ForexAI.spendSells, forexAI.ForexAI.symbol, forexAI.Configuration.tryExperimentalFeatures.
Referenced by forexAI.ForexAI.start.
int forexAI.ForexAI.CloseBuys()
References forexAI.ForexAI.buysCount, forexAI.ForexAI.charizedOrdersHistory, forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.CloseAllOrders.
int forexAI.ForexAI.CloseSells()
References forexAI.ForexAI.charizedOrdersHistory, forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.sellsCount, forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.CloseAllOrders.
void forexAI.ForexAI.OpenSell(double exactLots=0.0)
References forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.lastTradeBar, forexAI.ForexAI.lotsOptimizedV1, forexAI.Configuration.magickNumber, forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.CheckForMarketCollapse, forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
void forexAI.ForexAI.OpenBuy(double exactLots=0.0)
References forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.lastTradeBar, forexAI.ForexAI.lotsOptimizedV1, forexAI.Configuration.magickNumber, forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.CheckForMarketCollapse, forexAI.ForexAI.TryEnterCounterTrade, forexAI.ForexAI.TryEnterTrade.
void forexAI.ForexAI.TrailPositions()
References forexAI.ForexAI.activeOrders, forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.minStopLevel, forexAI.ForexAI.trailingBorder, forexAI.ForexAI.trailingStop.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.AddLabel(string text, Color clr)
References forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.AddVerticalLabel(string text, Color clr)
References forexAI.ForexAI.symbol.
Referenced by forexAI.ForexAI.CheckForMarketCollapse.
void forexAI.ForexAI.RenderVisualizedzedHistory()
References forexAI.ForexAI.charizedOrdersHistory, forexAI.ForexAI.profitBuys, forexAI.ForexAI.profitSells, forexAI.ForexAI.spendBuys, forexAI.ForexAI.spendSells.
Referenced by forexAI.ForexAI.start.
void forexAI.ForexAI.DumpInfo()
Referenced by forexAI.ForexAI.init.
void forexAI.ForexAI.ShowBanner()
References forexAI.ForexAI.version.
Referenced by forexAI.ForexAI.init.
void forexAI.ForexAI.DrawStats()
References forexAI.ForexAI.activeIncome, forexAI.ForexAI.activeLoss, forexAI.ForexAI.activeOrders, forexAI.ForexAI.activeProfit, forexAI.ForexAI.buyProbability, forexAI.ForexAI.dayOperationsCount, forexAI.ForexAI.forexFannNetwork, forexAI.ForexAI.inputDimension, forexAI.ForexAI.inputLayerActivationFunction, forexAI.ForexAI.isTrendStable, forexAI.ForexAI.labelID, forexAI.ForexAI.middleLayerActivationFunction, forexAI.ForexAI.networkFunctionsCount, forexAI.ForexAI.networkId, forexAI.ForexAI.prevBuyProbability, forexAI.ForexAI.prevSellProbability, forexAI.ForexAI.profit, forexAI.ForexAI.profitBuys, forexAI.ForexAI.profitSells, forexAI.ForexAI.sellProbability, forexAI.ForexAI.spendBuys, forexAI.ForexAI.spends, forexAI.ForexAI.spendSells, forexAI.ForexAI.testMse, forexAI.ForexAI.total, forexAI.ForexAI.totalOperationsCount, forexAI.ForexAI.totalProfits, forexAI.ForexAI.totalSpends, forexAI.ForexAI.tradeEnterProbabilityMin, forexAI.ForexAI.trainHitRatio, forexAI.ForexAI.trainMse.
Referenced by forexAI.ForexAI.start.