forexAI::YRandom
Random forexAI.YRandom.random
int forexAI.YRandom.prevResult
Referenced by forexAI.YRandom.between.
readonly RNGCryptoServiceProvider forexAI.YRandom._generator
static int forexAI.YRandom.Next(int n)
References forexAI.YRandom.between.
Referenced by forexAI.ForexAI.InitVariables, forexAI.ForexAI.start.
static int forexAI.YRandom.Next(int n, int m)
References forexAI.YRandom.between.
static int forexAI.YRandom.between(int minimumValue, int maximumValue)
References forexAI.YRandom.prevResult.
Referenced by forexAI.YRandom.Next.
static string forexAI.YRandom.randomString(int length=64)