forexAI::Logger
static int forexAI.Logger.GetCurrentThreadId()
Referenced by forexAI.Logger.console, forexAI.Logger.consolelog, forexAI.Logger.debug, forexAI.Logger.dump, forexAI.Logger.error, forexAI.Logger.info, forexAI.Logger.log, forexAI.Logger.notice, forexAI.Logger.warning.
static void forexAI.Logger.EraseLogs(params string[] fileNames)
References forexAI.Logger.console.
static void forexAI.Logger.ClearLogs()
References forexAI.Logger.console, forexAI.Helpers.IsFileBusy, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.dump(object data, string prefix="", string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.console(string lines, ConsoleColor bgcolor=Black, ConsoleColor fgcolor=White)
References forexAI.Logger.GetCurrentThreadId.
Referenced by forexAI.Logger.ClearLogs, forexAI.Logger.consolelog, forexAI.Logger.debug, forexAI.Logger.dump, forexAI.Logger.EraseLogs, forexAI.Logger.error, forexAI.Logger.info, forexAI.Logger.log, forexAI.Logger.notice, forexAI.Logger.warning.
static void forexAI.Logger.debug(string lines, string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.error(string lines, string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.info(string lines, string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.log(string lines, string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.logFileName, forexAI.Configuration.rootDirectory.
Referenced by forexAI.Logger.logIf.
static void forexAI.Logger.logIf(bool ifCase, string lines, string fileName=null)
References forexAI.Logger.log.
static void forexAI.Logger.consolelog(string lines, string fileName=null, ConsoleColor color=ConsoleColor.Cyan)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.logFileName, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.warning(string lines, string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.rootDirectory.
static void forexAI.Logger.notice(string lines, string fileName=null)
References forexAI.Logger.console, forexAI.Logger.GetCurrentThreadId, forexAI.Configuration.rootDirectory.