//......................../´¯)........... 
//.....................,/..../............ 
//..................../..../ ............. 
//............./´¯/' .../´¯/ ¯/\...... 
//........../'/.../... ./... /..././¯\.... 
//........('(....(.... (....(.. /'...).... 
//.........\................. ..\/..../.... 
//..........\......................./´..... 
//............\................ ..(........

using System;

namespace NQuotes.DebugHost
{
	public class Program
	{
		public static void Main(string[] args)
		{
			try
			{
				Server.Start(args);
			}
			catch (Exception e)
			{
				forexAI.Logger.console($"EXCEPTION:\r\n{e.Message} {e.StackTrace}", ConsoleColor.Black, ConsoleColor.Red);
			}
		}
	}
}
